spring.application.name=com.salesSavvy

spring.datasource.url = jdbc:mysql://localhost:3306/ecom
spring.datasource.username = root
spring.datasource.password = 1234
spring.jpa.hibernate.ddl-auto = update

razorpay.key.id     = rzp_test_jrPLsXS61Hckjt
razorpay.key.secret = ig02gYNHIfJrubUbiiGunKp2